const crypto = require("node:crypto");

var a = 21312;
var b = 312;

console.log("Hello World");

// pbkdf2: Password based key derivation function v2

// Sync fun (It will acutally block the main thread)
crypto.pbkdf2Sync("pass","salt", 5000000,50, "sha512");
console.log("Key is generated by blocking the thread (synchronously)")

// Async fun (Not blocking the thread)
crypto.pbkdf2("passs", "salt", 5000000, 50, "sha512", (err, key) => {
    console.log("Key is generated by not blocking the thread");
});

function multiply(a,b) {
    const res = a * b;
    return res;
};

const c = multiply(a,b);

console.log("Multiply res: ", c);